# SPDX-License-Identifier: GPL-2.0+
# Post-link processing for MIPS: populate .data.reloc section
# Called as: $(MAKE) -f arch/mips/Makefile.postlink <target>

include scripts/Kbuild.include
-include include/config/auto.conf

# Always run mips-relocs on the target ELF (e.g. u-boot, spl/u-boot-spl)
.PHONY: $(MAKECMDGOALS)
$(MAKECMDGOALS):
	$(MAKE) $(build)=tools tools/mips-relocs
	@printf "  RELOCS  %s\n" $@
	@tools/mips-relocs $@
